@host = https://prod.alsuperapi.com
# Local storage
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1NDM1MiwiZW1haWwiOiJzaGFya2VyOTJAaG90bWFpbC5jb20iLCJhdHRyaWJ1dGVzIjoiQW5kcmVzIE1vcmFsZXMgUmV5ZXMiLCJnZW5kZXIiOiJIIiwidHlwZSI6ImNsaWVudCIsImRhdGVfYmlydGgiOiIxOTkyLTA1LTExIiwibWVtYmVyc2hpcCI6IjAyMDk0NTk0NzA1NSIsImZpcmViYXNlX3Rva2VucyI6WyJmaDFDam9aU1EwNnJScDl0cElaM0RxOkFQQTkxYkVHQWZmcW5mTUVGX19jOGJPQ1R2enFQTHF5TFZfUG1HTWl4aUtvWkdWeGJyYjMwYWgxUnFzVzVpTFVHMHBkWGpJdEZwQ3I3Nlp0QjVMV3plUnFyNGlsTGJ2cGZrN2VXOHlkOENRUms5cHRQdllpUzJYMGtBejVPaTBab3NMWW5PSjVIVUlXIl0sImlhdCI6MTcxNTQ2NjM5M30.Kao3-uYfp6O1RBv44cFCT5eoYddG5QvFt-ehkYja2z8
###
# POST /cart/items
###
PUT {{host}}/cart/items/comments
Content-Type: application/json
Authorization: Bearer {{token}}

    {
    "name": "Brisket",
    "itemId": 14035,
    "quantity": 4.5,
    "branch_id": 6,
    "unit": "pza",
    "variant": null,
    "comment": "1 kilo",
    "unidad": "4.5 es la unidad por pieza calculada por alsuper"
  }
